core:
  port: "8088"
  worker_num: 8
  queue_num: 8192
  max_notification: 100
  mode: "release"
  ssl: false
  cert_path: "cert.pem"
  key_path: "key.pem"
  http_proxy: ""
  pid:
    enabled: false
    path: "gorush.pid"
    override: true

api:
  push_uri: "/api/push"
  stat_go_uri: "/api/stat/go"
  stat_app_uri: "/api/stat/app"
  config_uri: "/api/config"
  sys_stat_uri: "/sys/stats"

apps:
  default:
    android:
      enabled: true
      apikey: "YOUR_API_KEY"

    ios:
      enabled: false
      key_path: "key.pem"
      password: ""
      production: false

  paidVersion:
    android:
      enabled: true
      apikey: "YOUR_API_KEY"

    ios:
      enabled: false
      key_path: "key.pem"
      password: ""
      production: false

log:
  format: "string" # string or json
  access_log: "stdout"
  access_level: "debug"
  error_log: "stderr"
  error_level: "error"
  hide_token: true

stat:
  engine: "memory"
  redis:
    addr: "localhost:6379"
    password: ""
    db: 0
  boltdb:
    path: "bolt.db"
    bucket: "gorush"
  buntdb:
    path: "bunt.db"
  leveldb:
    path: "level.db"
